[2022-09-29 14:37:12,030] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: spark-setl3.spark_job_setl3 manual__2022-09-29T14:37:11.664958+00:00 [queued]>
[2022-09-29 14:37:12,039] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: spark-setl3.spark_job_setl3 manual__2022-09-29T14:37:11.664958+00:00 [queued]>
[2022-09-29 14:37:12,039] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-29 14:37:12,039] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-09-29 14:37:12,039] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-29 14:37:12,049] {taskinstance.py:1259} INFO - Executing <Task(SparkSubmitOperator): spark_job_setl3> on 2022-09-29 14:37:11.664958+00:00
[2022-09-29 14:37:12,055] {standard_task_runner.py:52} INFO - Started process 6576 to run task
[2022-09-29 14:37:12,057] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'spark-setl3', 'spark_job_setl3', 'manual__2022-09-29T14:37:11.664958+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/spark-setl-scala3.py', '--cfg-path', '/tmp/tmp3kvkq_x7', '--error-file', '/tmp/tmp572zdiud']
[2022-09-29 14:37:12,058] {standard_task_runner.py:77} INFO - Job 56: Subtask spark_job_setl3
[2022-09-29 14:37:12,093] {logging_mixin.py:109} INFO - Running <TaskInstance: spark-setl3.spark_job_setl3 manual__2022-09-29T14:37:11.664958+00:00 [running]> on host 4d693a43fffb
[2022-09-29 14:37:12,129] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***admin@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark-setl3
AIRFLOW_CTX_TASK_ID=spark_job_setl3
AIRFLOW_CTX_EXECUTION_DATE=2022-09-29T14:37:11.664958+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-29T14:37:11.664958+00:00
[2022-09-29 14:37:12,138] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://172.31.0.9, Port: 8080, Schema: , Login: ***, Password: ***, extra: {}
[2022-09-29 14:37:12,140] {spark_submit.py:334} INFO - Spark-Submit cmd: spark-submit --master spark://172.31.0.9:8080 --jars hdfs://172.31.0.3:8020/jars/setl_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar --class Job_s2t_AddTagVideo hdfs://172.31.0.3:8020/jars/setl_2.12-1.0.0-SNAPSHOT.jar
[2022-09-29 14:37:14,168] {spark_submit.py:485} INFO - 22/09/29 14:37:14 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2022-09-29 14:52:35,647] {spark_submit.py:485} INFO - Exception in thread "main" org.apache.hadoop.net.ConnectTimeoutException: Call From 4d693a43fffb/172.20.0.4 to 172.31.0.3:8020 failed on socket timeout exception: org.apache.hadoop.net.ConnectTimeoutException: 20000 millis timeout while waiting for channel to be ready for connect. ch : java.nio.channels.SocketChannel[connection-pending remote=172.31.0.3/172.31.0.3:8020]; For more details see:  http://wiki.apache.org/hadoop/SocketTimeout
[2022-09-29 14:52:35,648] {spark_submit.py:485} INFO - at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2022-09-29 14:52:35,648] {spark_submit.py:485} INFO - at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2022-09-29 14:52:35,648] {spark_submit.py:485} INFO - at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2022-09-29 14:52:35,648] {spark_submit.py:485} INFO - at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[2022-09-29 14:52:35,648] {spark_submit.py:485} INFO - at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:913)
[2022-09-29 14:52:35,648] {spark_submit.py:485} INFO - at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:848)
[2022-09-29 14:52:35,648] {spark_submit.py:485} INFO - at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1616)
[2022-09-29 14:52:35,648] {spark_submit.py:485} INFO - at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2022-09-29 14:52:35,648] {spark_submit.py:485} INFO - at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2022-09-29 14:52:35,649] {spark_submit.py:485} INFO - at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2022-09-29 14:52:35,649] {spark_submit.py:485} INFO - at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2022-09-29 14:52:35,649] {spark_submit.py:485} INFO - at com.sun.proxy.$Proxy26.getFileInfo(Unknown Source)
[2022-09-29 14:52:35,649] {spark_submit.py:485} INFO - at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:965)
[2022-09-29 14:52:35,649] {spark_submit.py:485} INFO - at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-09-29 14:52:35,649] {spark_submit.py:485} INFO - at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-09-29 14:52:35,649] {spark_submit.py:485} INFO - at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-09-29 14:52:35,649] {spark_submit.py:485} INFO - at java.lang.reflect.Method.invoke(Method.java:498)
[2022-09-29 14:52:35,649] {spark_submit.py:485} INFO - at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2022-09-29 14:52:35,649] {spark_submit.py:485} INFO - at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2022-09-29 14:52:35,650] {spark_submit.py:485} INFO - at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2022-09-29 14:52:35,650] {spark_submit.py:485} INFO - at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2022-09-29 14:52:35,650] {spark_submit.py:485} INFO - at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2022-09-29 14:52:35,650] {spark_submit.py:485} INFO - at com.sun.proxy.$Proxy27.getFileInfo(Unknown Source)
[2022-09-29 14:52:35,650] {spark_submit.py:485} INFO - at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1739)
[2022-09-29 14:52:35,650] {spark_submit.py:485} INFO - at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1753)
[2022-09-29 14:52:35,650] {spark_submit.py:485} INFO - at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1750)
[2022-09-29 14:52:35,650] {spark_submit.py:485} INFO - at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2022-09-29 14:52:35,650] {spark_submit.py:485} INFO - at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1765)
[2022-09-29 14:52:35,650] {spark_submit.py:485} INFO - at org.apache.hadoop.fs.Globber.getFileStatus(Globber.java:115)
[2022-09-29 14:52:35,650] {spark_submit.py:485} INFO - at org.apache.hadoop.fs.Globber.doGlob(Globber.java:349)
[2022-09-29 14:52:35,650] {spark_submit.py:485} INFO - at org.apache.hadoop.fs.Globber.glob(Globber.java:202)
[2022-09-29 14:52:35,650] {spark_submit.py:485} INFO - at org.apache.hadoop.fs.FileSystem.globStatus(FileSystem.java:2124)
[2022-09-29 14:52:35,650] {spark_submit.py:485} INFO - at org.apache.spark.util.DependencyUtils$.resolveGlobPath(DependencyUtils.scala:318)
[2022-09-29 14:52:35,650] {spark_submit.py:485} INFO - at org.apache.spark.util.DependencyUtils$.$anonfun$resolveGlobPaths$2(DependencyUtils.scala:273)
[2022-09-29 14:52:35,650] {spark_submit.py:485} INFO - at org.apache.spark.util.DependencyUtils$.$anonfun$resolveGlobPaths$2$adapted(DependencyUtils.scala:271)
[2022-09-29 14:52:35,650] {spark_submit.py:485} INFO - at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
[2022-09-29 14:52:35,650] {spark_submit.py:485} INFO - at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
[2022-09-29 14:52:35,651] {spark_submit.py:485} INFO - at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
[2022-09-29 14:52:35,651] {spark_submit.py:485} INFO - at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
[2022-09-29 14:52:35,651] {spark_submit.py:485} INFO - at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
[2022-09-29 14:52:35,651] {spark_submit.py:485} INFO - at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
[2022-09-29 14:52:35,651] {spark_submit.py:485} INFO - at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
[2022-09-29 14:52:35,651] {spark_submit.py:485} INFO - at org.apache.spark.util.DependencyUtils$.resolveGlobPaths(DependencyUtils.scala:271)
[2022-09-29 14:52:35,651] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit.$anonfun$prepareSubmitEnvironment$4(SparkSubmit.scala:364)
[2022-09-29 14:52:35,651] {spark_submit.py:485} INFO - at scala.Option.map(Option.scala:230)
[2022-09-29 14:52:35,651] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:364)
[2022-09-29 14:52:35,651] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:901)
[2022-09-29 14:52:35,651] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2022-09-29 14:52:35,651] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2022-09-29 14:52:35,651] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2022-09-29 14:52:35,651] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2022-09-29 14:52:35,651] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2022-09-29 14:52:35,651] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2022-09-29 14:52:35,651] {spark_submit.py:485} INFO - Caused by: org.apache.hadoop.net.ConnectTimeoutException: 20000 millis timeout while waiting for channel to be ready for connect. ch : java.nio.channels.SocketChannel[connection-pending remote=172.31.0.3/172.31.0.3:8020]
[2022-09-29 14:52:35,651] {spark_submit.py:485} INFO - at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:589)
[2022-09-29 14:52:35,651] {spark_submit.py:485} INFO - at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:711)
[2022-09-29 14:52:35,651] {spark_submit.py:485} INFO - at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:833)
[2022-09-29 14:52:35,652] {spark_submit.py:485} INFO - at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:414)
[2022-09-29 14:52:35,652] {spark_submit.py:485} INFO - at org.apache.hadoop.ipc.Client.getConnection(Client.java:1677)
[2022-09-29 14:52:35,652] {spark_submit.py:485} INFO - at org.apache.hadoop.ipc.Client.call(Client.java:1502)
[2022-09-29 14:52:35,652] {spark_submit.py:485} INFO - ... 45 more
[2022-09-29 14:52:35,700] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 417, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://172.31.0.9:8080 --jars hdfs://172.31.0.3:8020/jars/setl_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar --class Job_s2t_AddTagVideo hdfs://172.31.0.3:8020/jars/setl_2.12-1.0.0-SNAPSHOT.jar. Error code is: 1.
[2022-09-29 14:52:35,705] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=spark-setl3, task_id=spark_job_setl3, execution_date=20220929T143711, start_date=20220929T143712, end_date=20220929T145235
[2022-09-29 14:52:35,715] {standard_task_runner.py:92} ERROR - Failed to execute job 56 for task spark_job_setl3
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 417, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://172.31.0.9:8080 --jars hdfs://172.31.0.3:8020/jars/setl_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar --class Job_s2t_AddTagVideo hdfs://172.31.0.3:8020/jars/setl_2.12-1.0.0-SNAPSHOT.jar. Error code is: 1.
[2022-09-29 14:52:35,750] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-09-29 14:52:35,779] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
