[2022-10-04 03:29:41,433] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: spark-setl3.spark_job_setl3 manual__2022-10-04T03:28:31.483893+00:00 [queued]>
[2022-10-04 03:29:41,439] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: spark-setl3.spark_job_setl3 manual__2022-10-04T03:28:31.483893+00:00 [queued]>
[2022-10-04 03:29:41,440] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-10-04 03:29:41,440] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-10-04 03:29:41,440] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-10-04 03:29:41,446] {taskinstance.py:1259} INFO - Executing <Task(SparkSubmitOperator): spark_job_setl3> on 2022-10-04 03:28:31.483893+00:00
[2022-10-04 03:29:41,451] {standard_task_runner.py:52} INFO - Started process 3149 to run task
[2022-10-04 03:29:41,452] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'spark-setl3', 'spark_job_setl3', 'manual__2022-10-04T03:28:31.483893+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/spark-setl-scala3.py', '--cfg-path', '/tmp/tmp_nbc3_nj', '--error-file', '/tmp/tmp8787vb6_']
[2022-10-04 03:29:41,453] {standard_task_runner.py:77} INFO - Job 54: Subtask spark_job_setl3
[2022-10-04 03:29:41,481] {logging_mixin.py:109} INFO - Running <TaskInstance: spark-setl3.spark_job_setl3 manual__2022-10-04T03:28:31.483893+00:00 [running]> on host df2389ffd8bb
[2022-10-04 03:29:41,514] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***admin@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark-setl3
AIRFLOW_CTX_TASK_ID=spark_job_setl3
AIRFLOW_CTX_EXECUTION_DATE=2022-10-04T03:28:31.483893+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-04T03:28:31.483893+00:00
[2022-10-04 03:29:41,520] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://10.0.9.226, Port: 7077, Schema: , Login: ***, Password: ***, extra: {'deploy-mode': 'cluster'}
[2022-10-04 03:29:41,522] {spark_submit.py:334} INFO - Spark-Submit cmd: spark-submit --master spark://10.0.9.226:7077 --jars hdfs://10.0.9.226:8020/tmp/jars/setl_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar --class Job_s2t_AddTagVideo --deploy-mode cluster hdfs://10.0.9.226:8020/tmp/jars/setl_2.12-1.0.0-SNAPSHOT.jar
[2022-10-04 03:29:42,896] {spark_submit.py:485} INFO - 22/10/04 03:29:42 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2022-10-04 03:29:43,383] {spark_submit.py:485} INFO - 22/10/04 03:29:43 INFO SecurityManager: Changing view acls to: default
[2022-10-04 03:29:43,383] {spark_submit.py:485} INFO - 22/10/04 03:29:43 INFO SecurityManager: Changing modify acls to: default
[2022-10-04 03:29:43,383] {spark_submit.py:485} INFO - 22/10/04 03:29:43 INFO SecurityManager: Changing view acls groups to:
[2022-10-04 03:29:43,384] {spark_submit.py:485} INFO - 22/10/04 03:29:43 INFO SecurityManager: Changing modify acls groups to:
[2022-10-04 03:29:43,384] {spark_submit.py:485} INFO - 22/10/04 03:29:43 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(default); groups with view permissions: Set(); users  with modify permissions: Set(default); groups with modify permissions: Set()
[2022-10-04 03:29:43,631] {spark_submit.py:485} INFO - 22/10/04 03:29:43 INFO Utils: Successfully started service 'driverClient' on port 41631.
[2022-10-04 03:29:43,675] {spark_submit.py:485} INFO - 22/10/04 03:29:43 INFO TransportClientFactory: Successfully created connection to /10.0.9.226:7077 after 25 ms (0 ms spent in bootstraps)
[2022-10-04 03:29:43,822] {spark_submit.py:485} INFO - 22/10/04 03:29:43 INFO ClientEndpoint: ... waiting before polling master for driver state
[2022-10-04 03:29:43,845] {spark_submit.py:483} INFO - identified spark driver id: driver-20221004032943-0002
[2022-10-04 03:29:43,845] {spark_submit.py:485} INFO - 22/10/04 03:29:43 INFO ClientEndpoint: Driver successfully submitted as driver-20221004032943-0002
[2022-10-04 03:29:48,873] {spark_submit.py:485} INFO - 22/10/04 03:29:48 INFO ClientEndpoint: State of driver-20221004032943-0002 is ERROR
[2022-10-04 03:29:48,873] {spark_submit.py:485} INFO - 22/10/04 03:29:48 ERROR ClientEndpoint: Exception from cluster was: java.io.FileNotFoundException: File hdfs://10.0.9.226:8020/tmp/jars/setl_2.12-1.0.0-SNAPSHOT.jar does not exist.
[2022-10-04 03:29:48,873] {spark_submit.py:485} INFO - java.io.FileNotFoundException: File hdfs://10.0.9.226:8020/tmp/jars/setl_2.12-1.0.0-SNAPSHOT.jar does not exist.
[2022-10-04 03:29:48,873] {spark_submit.py:485} INFO - at org.apache.hadoop.hdfs.DistributedFileSystem.listStatusInternal(DistributedFileSystem.java:1103)
[2022-10-04 03:29:48,873] {spark_submit.py:485} INFO - at org.apache.hadoop.hdfs.DistributedFileSystem.access$600(DistributedFileSystem.java:146)
[2022-10-04 03:29:48,873] {spark_submit.py:485} INFO - at org.apache.hadoop.hdfs.DistributedFileSystem$24.doCall(DistributedFileSystem.java:1174)
[2022-10-04 03:29:48,873] {spark_submit.py:485} INFO - at org.apache.hadoop.hdfs.DistributedFileSystem$24.doCall(DistributedFileSystem.java:1171)
[2022-10-04 03:29:48,873] {spark_submit.py:485} INFO - at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2022-10-04 03:29:48,873] {spark_submit.py:485} INFO - at org.apache.hadoop.hdfs.DistributedFileSystem.listStatus(DistributedFileSystem.java:1181)
[2022-10-04 03:29:48,873] {spark_submit.py:485} INFO - at org.apache.spark.util.Utils$.fetchHcfsFile(Utils.scala:814)
[2022-10-04 03:29:48,873] {spark_submit.py:485} INFO - at org.apache.spark.util.Utils$.doFetchFile(Utils.scala:783)
[2022-10-04 03:29:48,873] {spark_submit.py:485} INFO - at org.apache.spark.util.Utils$.fetchFile(Utils.scala:549)
[2022-10-04 03:29:48,873] {spark_submit.py:485} INFO - at org.apache.spark.deploy.worker.DriverRunner.downloadUserJar(DriverRunner.scala:162)
[2022-10-04 03:29:48,874] {spark_submit.py:485} INFO - at org.apache.spark.deploy.worker.DriverRunner.prepareAndRunDriver(DriverRunner.scala:179)
[2022-10-04 03:29:48,874] {spark_submit.py:485} INFO - at org.apache.spark.deploy.worker.DriverRunner$$anon$2.run(DriverRunner.scala:99)
[2022-10-04 03:29:48,875] {spark_submit.py:485} INFO - 22/10/04 03:29:48 INFO ShutdownHookManager: Shutdown hook called
[2022-10-04 03:29:48,875] {spark_submit.py:485} INFO - 22/10/04 03:29:48 INFO ShutdownHookManager: Deleting directory /tmp/spark-b5d78eed-4cdb-48e2-b39b-26bbed003f77
[2022-10-04 03:29:49,232] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 417, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://10.0.9.226:7077 --jars hdfs://10.0.9.226:8020/tmp/jars/setl_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar --class Job_s2t_AddTagVideo --deploy-mode cluster hdfs://10.0.9.226:8020/tmp/jars/setl_2.12-1.0.0-SNAPSHOT.jar. Error code is: 255.
[2022-10-04 03:29:49,239] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=spark-setl3, task_id=spark_job_setl3, execution_date=20221004T032831, start_date=20221004T032941, end_date=20221004T032949
[2022-10-04 03:29:49,250] {standard_task_runner.py:92} ERROR - Failed to execute job 54 for task spark_job_setl3
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 417, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://10.0.9.226:7077 --jars hdfs://10.0.9.226:8020/tmp/jars/setl_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar --class Job_s2t_AddTagVideo --deploy-mode cluster hdfs://10.0.9.226:8020/tmp/jars/setl_2.12-1.0.0-SNAPSHOT.jar. Error code is: 255.
[2022-10-04 03:29:49,282] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-10-04 03:29:49,321] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
