[2022-09-30 08:27:29,492] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: spark-setl3.spark_job_setl3 manual__2022-09-30T08:22:04.634175+00:00 [queued]>
[2022-09-30 08:27:29,501] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: spark-setl3.spark_job_setl3 manual__2022-09-30T08:22:04.634175+00:00 [queued]>
[2022-09-30 08:27:29,501] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-30 08:27:29,501] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-09-30 08:27:29,501] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-30 08:27:29,510] {taskinstance.py:1259} INFO - Executing <Task(SparkSubmitOperator): spark_job_setl3> on 2022-09-30 08:22:04.634175+00:00
[2022-09-30 08:27:29,514] {standard_task_runner.py:52} INFO - Started process 842 to run task
[2022-09-30 08:27:29,516] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'spark-setl3', 'spark_job_setl3', 'manual__2022-09-30T08:22:04.634175+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/spark-setl-scala3.py', '--cfg-path', '/tmp/tmpwn4i256o', '--error-file', '/tmp/tmpnfti3lbw']
[2022-09-30 08:27:29,516] {standard_task_runner.py:77} INFO - Job 67: Subtask spark_job_setl3
[2022-09-30 08:27:29,547] {logging_mixin.py:109} INFO - Running <TaskInstance: spark-setl3.spark_job_setl3 manual__2022-09-30T08:22:04.634175+00:00 [running]> on host 3b110e72e73c
[2022-09-30 08:27:29,580] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***admin@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark-setl3
AIRFLOW_CTX_TASK_ID=spark_job_setl3
AIRFLOW_CTX_EXECUTION_DATE=2022-09-30T08:22:04.634175+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-30T08:22:04.634175+00:00
[2022-09-30 08:27:29,587] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://10.0.9.226, Port: 7077, Schema: , Login: ***, Password: ***, extra: {}
[2022-09-30 08:27:29,587] {spark_submit.py:334} INFO - Spark-Submit cmd: spark-submit --master spark://10.0.9.226:7077 --jars hdfs://10.0.9.226:8020/jars/setl_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar --class Job_s2t_AddTagVideo hdfs://10.0.9.226:8020/jars/setl_2.12-1.0.0-SNAPSHOT.jar
[2022-09-30 08:27:31,054] {spark_submit.py:485} INFO - 22/09/30 08:27:31 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2022-09-30 08:27:31,865] {spark_submit.py:485} INFO - Exception in thread "main" java.io.FileNotFoundException: File hdfs://10.0.9.226:8020/jars/setl_2.12-1.0.0-SNAPSHOT.jar does not exist.
[2022-09-30 08:27:31,865] {spark_submit.py:485} INFO - at org.apache.hadoop.hdfs.DistributedFileSystem.listStatusInternal(DistributedFileSystem.java:1104)
[2022-09-30 08:27:31,865] {spark_submit.py:485} INFO - at org.apache.hadoop.hdfs.DistributedFileSystem.access$600(DistributedFileSystem.java:147)
[2022-09-30 08:27:31,865] {spark_submit.py:485} INFO - at org.apache.hadoop.hdfs.DistributedFileSystem$24.doCall(DistributedFileSystem.java:1175)
[2022-09-30 08:27:31,865] {spark_submit.py:485} INFO - at org.apache.hadoop.hdfs.DistributedFileSystem$24.doCall(DistributedFileSystem.java:1172)
[2022-09-30 08:27:31,865] {spark_submit.py:485} INFO - at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2022-09-30 08:27:31,865] {spark_submit.py:485} INFO - at org.apache.hadoop.hdfs.DistributedFileSystem.listStatus(DistributedFileSystem.java:1182)
[2022-09-30 08:27:31,865] {spark_submit.py:485} INFO - at org.apache.spark.util.Utils$.fetchHcfsFile(Utils.scala:851)
[2022-09-30 08:27:31,865] {spark_submit.py:485} INFO - at org.apache.spark.util.Utils$.doFetchFile(Utils.scala:820)
[2022-09-30 08:27:31,865] {spark_submit.py:485} INFO - at org.apache.spark.util.DependencyUtils$.downloadFile(DependencyUtils.scala:264)
[2022-09-30 08:27:31,865] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit.$anonfun$prepareSubmitEnvironment$8(SparkSubmit.scala:376)
[2022-09-30 08:27:31,866] {spark_submit.py:485} INFO - at scala.Option.map(Option.scala:230)
[2022-09-30 08:27:31,866] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:376)
[2022-09-30 08:27:31,866] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:901)
[2022-09-30 08:27:31,866] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2022-09-30 08:27:31,866] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2022-09-30 08:27:31,866] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2022-09-30 08:27:31,866] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2022-09-30 08:27:31,866] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2022-09-30 08:27:31,866] {spark_submit.py:485} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2022-09-30 08:27:31,917] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 417, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://10.0.9.226:7077 --jars hdfs://10.0.9.226:8020/jars/setl_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar --class Job_s2t_AddTagVideo hdfs://10.0.9.226:8020/jars/setl_2.12-1.0.0-SNAPSHOT.jar. Error code is: 1.
[2022-09-30 08:27:31,923] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=spark-setl3, task_id=spark_job_setl3, execution_date=20220930T082204, start_date=20220930T082729, end_date=20220930T082731
[2022-09-30 08:27:31,934] {standard_task_runner.py:92} ERROR - Failed to execute job 67 for task spark_job_setl3
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 417, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://10.0.9.226:7077 --jars hdfs://10.0.9.226:8020/jars/setl_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar --class Job_s2t_AddTagVideo hdfs://10.0.9.226:8020/jars/setl_2.12-1.0.0-SNAPSHOT.jar. Error code is: 1.
[2022-09-30 08:27:31,975] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-09-30 08:27:31,995] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
